channels:
- defaults
- conda-forge
dependencies:
- python=3.6.6
- numpy=1.14.5
- scipy=1.1.0
- scikit-learn=0.20.1
- tornado=4.5.3
- jupyter=1.0.0
- jupyterlab=0.34.9
- jupyter_contrib_nbextensions=0.5.0
- jupyter_nbextensions_configurator=0.4.0
- pandas=0.23.4
- seaborn=0.9.0
- plotly=3.2.1
- matplotlib
- notebook=5.6.0
- ipykernel=4.10.0
- ipywidgets=7.4.1
- nbconvert=5.4.0
- keras=2.2.4
- tensorflow=1.12
- watermark
- pytest=3.6.2
- autopep8
- pylint
- pep8=1.7.1
- pylama=7.4.3
- pip=18.0
